### ISSUE TITLE
Settle on a linting config for ESLint

### ISSUE THREAD

**Issue by johndturn** [ngoue/isthismoviegoodorbad#3]
Please post opinions about it here in this issue.

**Comment by johndturn** [comment]
I personally have always used AirBnb's eslint config for my projects, with some small modifications to have `prettier`'s config / choices take precedence. It's always resulted in a solid, consistent style.

**Comment by tgroshon** [comment]
Doesn’t CRA already have an ESLint config?

**Comment by tgroshon** [comment]
Also, for projects using TyoeScript and Prettier already, eslint is pretty redundant

**Comment by johndturn** [comment]
I agree that ESLint can be redundant in certain cases, but given the ability to use certain plugins, it can benefit projects quite a bit. 

For example, the AirBNB's style guide makes heavy use of the a11y Eslint plugin*, which will promote (though it's not a silver bullet) more accessible markup. For someone like me, who doesn't write the most semantic / accessible code by default, and for newer devs, this can really help enforce more accessible JS and markup. 

There are also things that ESLint can break a build with that TS ignores and that Prettier doesn't concern itself with. One example is unused imports. ESLint can flag this and throw an error, while TS doesn't care about it (from my experience). 

All in all, I think that you're right that there's a lot of overlap in the Venn diagram if you look at it that way, but each tool has things that it brings to the table that others don't cover. 

*Another reason to use the AirBNB's eslint config, cause I don't want to have to configure the a11y plugin myself, as AirBNB's config is already an industry standard, especially for React.

**Comment by johndturn** [comment]
> Doesn’t CRA already have an ESLint config?

Yes it does, and it covers certain things. However, it doesn't involve plugins like a11y that AirBNB covers.

**Comment by tgroshon** [comment]
The included `react-app` eslint config courtesy of CRA uses all of the same plugins as the AirBNB configs:

  - eslint-plugin-import
  - eslint-plugin-react
  - eslint-plugin-react-hooks
  - eslint-plugin-jsx-a11y
 
The two configs primarily take different approaches with regards to their actual plugin and rule settings.

Generally, I dislike all eslint configurations that act as "style guides" and prefer only configs that perform static analysis to give warnings, errors, etc. related to the substance of the code (ie "line unreachable", "missing deps in hook", etc.).  All other "code style" should either be autoformattable via prettier, enforced by code reviews, or more often than not *ignored*.  AirBnb is a mostly a style-guide, while `react-app` is exclusively static analysis.

Specific to AirBnB, I _strongly dislike_ their ESLint configs and disagree with a ton of their react-specific settings.  For example, they enforce "one component per file" and that's an ESLint rule I actively campaign against as stupid and harmful.  AirBnb configs have been around _forever_ and come out of a time before Prettier when everyone enforced their snowflake "styles" via ESLint.  The AirBnb configs have never really graduated beyond that.  Now, we let prettier do all meaningful formatting and styling automagically and agree that all other "style choices" are probably irrelevant (I think they are).

Remember, we're not building this project for new developers, we're building it for us: mature developers with years worth of our own opinions and experiences who have already worked together for a long-time.  This project is most likely to fail because we get bored, busy, or frustrated; not because we get bogged down by code consistency or aesthetics.  For that reason, I think it's best to take a light touch with tooling to reduce dev overhead.

**My Preference:** Prettier + default `react-app` ESLint config :+1:

**Comment by tgroshon** [comment]
Will close this tomorrow if no further discussion.

**Comment by ngoue** [comment]
Yeah, I agree with what you guys said.
